/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadAllRouteImport } from './routes/api/download-all'
import { Route as ApiConvertRouteImport } from './routes/api/convert'
import { Route as ApiFilesCacheIdRouteImport } from './routes/api/files/$cacheId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadAllRoute = ApiDownloadAllRouteImport.update({
  id: '/api/download-all',
  path: '/api/download-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertRoute = ApiConvertRouteImport.update({
  id: '/api/convert',
  path: '/api/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesCacheIdRoute = ApiFilesCacheIdRouteImport.update({
  id: '/api/files/$cacheId',
  path: '/api/files/$cacheId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/download-all': typeof ApiDownloadAllRoute
  '/api/files/$cacheId': typeof ApiFilesCacheIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/download-all': typeof ApiDownloadAllRoute
  '/api/files/$cacheId': typeof ApiFilesCacheIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/convert': typeof ApiConvertRoute
  '/api/download-all': typeof ApiDownloadAllRoute
  '/api/files/$cacheId': typeof ApiFilesCacheIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/convert' | '/api/download-all' | '/api/files/$cacheId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/convert' | '/api/download-all' | '/api/files/$cacheId'
  id:
    | '__root__'
    | '/'
    | '/api/convert'
    | '/api/download-all'
    | '/api/files/$cacheId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConvertRoute: typeof ApiConvertRoute
  ApiDownloadAllRoute: typeof ApiDownloadAllRoute
  ApiFilesCacheIdRoute: typeof ApiFilesCacheIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-all': {
      id: '/api/download-all'
      path: '/api/download-all'
      fullPath: '/api/download-all'
      preLoaderRoute: typeof ApiDownloadAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert': {
      id: '/api/convert'
      path: '/api/convert'
      fullPath: '/api/convert'
      preLoaderRoute: typeof ApiConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$cacheId': {
      id: '/api/files/$cacheId'
      path: '/api/files/$cacheId'
      fullPath: '/api/files/$cacheId'
      preLoaderRoute: typeof ApiFilesCacheIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConvertRoute: ApiConvertRoute,
  ApiDownloadAllRoute: ApiDownloadAllRoute,
  ApiFilesCacheIdRoute: ApiFilesCacheIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
